### ISSUE TITLE
Permissions are... broken? Cannot set mapping whitelist

### ISSUE THREAD

**Issue by triphora** [linkie/linkie-discord#14]
Per the recent Quilt RFC, Consistency Plus (server ID 807804499141328904) decided to ditch our cleanroom and allow Linkie to do mappings other than Yarn & Plasma. Our first issue was that the `!value` command no longer works, only `/value`... once we got that figured out, we weren't able to set `mappings.whitelist` to null. Setting it to `null` doesn't allow any mappings at all (I guess because it's treating it as a string instead of a boolean, but there's no way to distinguish which one you set it as) but setting it to `yarn, plasma, mojang, mcp` doesn't work either, so now we're not able to look up any mappings at all. Any help with this?

**Comment by triphora** [comment]
Well, we figured out that it was the spaces between (e.g. `yarn, plasma` instead of `yarn,plasma`) causing the issue. The two issues with **only slash commands working for value commands** and **being unable to set a value to null** persist.

**Comment by shedaniel** [comment]
Thanks for reporting, there seems to be currently some issues with parsing sub commands after the introduction of an unified command system, hopefully to resolve this in the future to add a unset command as well.
