### ISSUE TITLE
Can not add or remove tricks

### ISSUE THREAD

**Issue by Waoweens** [linkie/linkie-discord#15]
![IMG_20210817_171253.jpg](https://user-images.githubusercontent.com/30313089/129708144-ce72453d-b0dc-41d9-884c-e2ae1b55d872.jpg)

![IMG_20210817_171306.jpg](https://user-images.githubusercontent.com/30313089/129708179-c045bfc7-a2e4-4225-ad96-cec314d6358b.jpg)

**Comment by shedaniel** [comment]
Please consider using the slash command variant for now, this is a bug.
